# Get the stop words

In [18]:
import nltk
from nltk.corpus import stopwords
import re
import numpy

# Tokenize All Sentences

In [6]:
def word_extraction(sentence):
    ignore = set(stopwords.words('english'))
    words = re.sub("[^\w]", " ",  sentence).split()
    cleaned_text = [w.lower() for w in words if w not in ignore]
    return cleaned_text

# Apply tokenization to all sentences

In [11]:
def tokenize(sentences):
    words = []
    for sentence in sentences:
        w = word_extraction(sentence)
        words.extend(w)
        words = sorted(list(set(words)))
    return words

# Build vocabulary and generate vectors

In [12]:
def generate_bow(allsentences):        
    vocab = tokenize(allsentences)    
    print("Word List for Document \n{0} \n".format(vocab))
    for sentence in allsentences:        
        words = word_extraction(sentence)        
        bag_vector = numpy.zeros(len(vocab))        
        for w in words:            
            for i,word in enumerate(vocab):                
                if word == w:                     
                    bag_vector[i] += 1                            
        print("{0}\n{1}\n".format(sentence,numpy.array(bag_vector)))

# Test the Function

In [16]:
allsentences = ["Joe waited for the train train", "The train was late", "Mary and Samantha took the bus"]

In [19]:
generate_bow(allsentences)

Word List for Document 
['bus', 'joe', 'late', 'mary', 'samantha', 'the', 'took', 'train', 'waited'] 

Joe waited for the train train
[0. 1. 0. 0. 0. 0. 0. 2. 1.]

The train was late
[0. 0. 1. 0. 0. 1. 0. 1. 0.]

Mary and Samantha took the bus
[1. 0. 0. 1. 1. 0. 1. 0. 0.]

